from fedora:35

RUN dnf install -y git gcc perl-interpreter make autoconf automake libtool perf strace valgrind vim
RUN git clone https://github.com/nokia/asn1c.git
RUN cd asn1c && autoreconf -iv && ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --docdir=/usr/share/doc/asn1c && make && make install
